# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: password.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0epassword.proto\":\n\x14\x45ncryptStringRequest\x12\x14\n\x0c\x65ncrypt_type\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\"/\n\x15\x45ncryptStringResponse\x12\x16\n\x0e\x62\x61se64_encrypt\x18\x01 \x01(\t\"D\n\x14\x44\x65\x63ryptStringRequest\x12\x14\n\x0c\x65ncrypt_type\x18\x01 \x01(\t\x12\x16\n\x0e\x62\x61se64_encrypt\x18\x02 \x01(\t\"-\n\x15\x44\x65\x63ryptStringResponse\x12\x14\n\x0c\x64\x65\x63rypt_data\x18\x01 \x01(\t2\x90\x01\n\x0eServerPassword\x12>\n\rEncryptString\x12\x15.EncryptStringRequest\x1a\x16.EncryptStringResponse\x12>\n\rDecryptString\x12\x15.DecryptStringRequest\x1a\x16.DecryptStringResponseB\nZ\x08../protob\x06proto3')



_ENCRYPTSTRINGREQUEST = DESCRIPTOR.message_types_by_name['EncryptStringRequest']
_ENCRYPTSTRINGRESPONSE = DESCRIPTOR.message_types_by_name['EncryptStringResponse']
_DECRYPTSTRINGREQUEST = DESCRIPTOR.message_types_by_name['DecryptStringRequest']
_DECRYPTSTRINGRESPONSE = DESCRIPTOR.message_types_by_name['DecryptStringResponse']
EncryptStringRequest = _reflection.GeneratedProtocolMessageType('EncryptStringRequest', (_message.Message,), {
  'DESCRIPTOR' : _ENCRYPTSTRINGREQUEST,
  '__module__' : 'password_pb2'
  # @@protoc_insertion_point(class_scope:EncryptStringRequest)
  })
_sym_db.RegisterMessage(EncryptStringRequest)

EncryptStringResponse = _reflection.GeneratedProtocolMessageType('EncryptStringResponse', (_message.Message,), {
  'DESCRIPTOR' : _ENCRYPTSTRINGRESPONSE,
  '__module__' : 'password_pb2'
  # @@protoc_insertion_point(class_scope:EncryptStringResponse)
  })
_sym_db.RegisterMessage(EncryptStringResponse)

DecryptStringRequest = _reflection.GeneratedProtocolMessageType('DecryptStringRequest', (_message.Message,), {
  'DESCRIPTOR' : _DECRYPTSTRINGREQUEST,
  '__module__' : 'password_pb2'
  # @@protoc_insertion_point(class_scope:DecryptStringRequest)
  })
_sym_db.RegisterMessage(DecryptStringRequest)

DecryptStringResponse = _reflection.GeneratedProtocolMessageType('DecryptStringResponse', (_message.Message,), {
  'DESCRIPTOR' : _DECRYPTSTRINGRESPONSE,
  '__module__' : 'password_pb2'
  # @@protoc_insertion_point(class_scope:DecryptStringResponse)
  })
_sym_db.RegisterMessage(DecryptStringResponse)

_SERVERPASSWORD = DESCRIPTOR.services_by_name['ServerPassword']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\010../proto'
  _ENCRYPTSTRINGREQUEST._serialized_start=18
  _ENCRYPTSTRINGREQUEST._serialized_end=76
  _ENCRYPTSTRINGRESPONSE._serialized_start=78
  _ENCRYPTSTRINGRESPONSE._serialized_end=125
  _DECRYPTSTRINGREQUEST._serialized_start=127
  _DECRYPTSTRINGREQUEST._serialized_end=195
  _DECRYPTSTRINGRESPONSE._serialized_start=197
  _DECRYPTSTRINGRESPONSE._serialized_end=242
  _SERVERPASSWORD._serialized_start=245
  _SERVERPASSWORD._serialized_end=389
# @@protoc_insertion_point(module_scope)
