# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: password.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0epassword.proto\"%\n\x0e\x45ncryptRequest\x12\x13\n\x0b\x62\x61se64_data\x18\x01 \x01(\t\")\n\x0f\x45ncryptResponse\x12\x16\n\x0e\x62\x61se64_encrypt\x18\x01 \x01(\t29\n\tServerAes\x12,\n\x07\x45ncrypt\x12\x0f.EncryptRequest\x1a\x10.EncryptResponseB\nZ\x08../protob\x06proto3')



_ENCRYPTREQUEST = DESCRIPTOR.message_types_by_name['EncryptRequest']
_ENCRYPTRESPONSE = DESCRIPTOR.message_types_by_name['EncryptResponse']
EncryptRequest = _reflection.GeneratedProtocolMessageType('EncryptRequest', (_message.Message,), {
  'DESCRIPTOR' : _ENCRYPTREQUEST,
  '__module__' : 'password_pb2'
  # @@protoc_insertion_point(class_scope:EncryptRequest)
  })
_sym_db.RegisterMessage(EncryptRequest)

EncryptResponse = _reflection.GeneratedProtocolMessageType('EncryptResponse', (_message.Message,), {
  'DESCRIPTOR' : _ENCRYPTRESPONSE,
  '__module__' : 'password_pb2'
  # @@protoc_insertion_point(class_scope:EncryptResponse)
  })
_sym_db.RegisterMessage(EncryptResponse)

_SERVERAES = DESCRIPTOR.services_by_name['ServerAes']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\010../proto'
  _ENCRYPTREQUEST._serialized_start=18
  _ENCRYPTREQUEST._serialized_end=55
  _ENCRYPTRESPONSE._serialized_start=57
  _ENCRYPTRESPONSE._serialized_end=98
  _SERVERAES._serialized_start=100
  _SERVERAES._serialized_end=157
# @@protoc_insertion_point(module_scope)
