# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: captcha.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcaptcha.proto\"\x1e\n\rCreateRequest\x12\r\n\x05\x63type\x18\x01 \x01(\t\".\n\x0e\x43reateResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08question\x18\x02 \x01(\t\":\n\rVerifyRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x63type\x18\x02 \x01(\t\x12\x0e\n\x06\x61nswer\x18\x03 \x01(\t\" \n\x0eVerifyResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x32\x65\n\rServerCaptcha\x12)\n\x06\x43reate\x12\x0e.CreateRequest\x1a\x0f.CreateResponse\x12)\n\x06Verify\x12\x0e.VerifyRequest\x1a\x0f.VerifyResponseB\nZ\x08../protob\x06proto3')



_CREATEREQUEST = DESCRIPTOR.message_types_by_name['CreateRequest']
_CREATERESPONSE = DESCRIPTOR.message_types_by_name['CreateResponse']
_VERIFYREQUEST = DESCRIPTOR.message_types_by_name['VerifyRequest']
_VERIFYRESPONSE = DESCRIPTOR.message_types_by_name['VerifyResponse']
CreateRequest = _reflection.GeneratedProtocolMessageType('CreateRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEREQUEST,
  '__module__' : 'captcha_pb2'
  # @@protoc_insertion_point(class_scope:CreateRequest)
  })
_sym_db.RegisterMessage(CreateRequest)

CreateResponse = _reflection.GeneratedProtocolMessageType('CreateResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATERESPONSE,
  '__module__' : 'captcha_pb2'
  # @@protoc_insertion_point(class_scope:CreateResponse)
  })
_sym_db.RegisterMessage(CreateResponse)

VerifyRequest = _reflection.GeneratedProtocolMessageType('VerifyRequest', (_message.Message,), {
  'DESCRIPTOR' : _VERIFYREQUEST,
  '__module__' : 'captcha_pb2'
  # @@protoc_insertion_point(class_scope:VerifyRequest)
  })
_sym_db.RegisterMessage(VerifyRequest)

VerifyResponse = _reflection.GeneratedProtocolMessageType('VerifyResponse', (_message.Message,), {
  'DESCRIPTOR' : _VERIFYRESPONSE,
  '__module__' : 'captcha_pb2'
  # @@protoc_insertion_point(class_scope:VerifyResponse)
  })
_sym_db.RegisterMessage(VerifyResponse)

_SERVERCAPTCHA = DESCRIPTOR.services_by_name['ServerCaptcha']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\010../proto'
  _CREATEREQUEST._serialized_start=17
  _CREATEREQUEST._serialized_end=47
  _CREATERESPONSE._serialized_start=49
  _CREATERESPONSE._serialized_end=95
  _VERIFYREQUEST._serialized_start=97
  _VERIFYREQUEST._serialized_end=155
  _VERIFYRESPONSE._serialized_start=157
  _VERIFYRESPONSE._serialized_end=189
  _SERVERCAPTCHA._serialized_start=191
  _SERVERCAPTCHA._serialized_end=292
# @@protoc_insertion_point(module_scope)
